global:
  scrape_interval: "10s"
  evaluation_interval: "10s"

scrape_configs:
  - job_name: 'gatewayprojet_service'
    scrape_interval: 10s   # Augmenter l'intervalle à 10s
    scrape_timeout: 15s    # Augmenter le délai à 15s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.9:8888']
        labels:
          application: 'my gateway service application'